# **Level 2**
## **Task 1: Table Booking and Online Delivery**

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv(r'cleaned_dataset.csv')
data

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,stanbul,"Kemanke Karamustafa Paa Mahallesi, R۱ht۱m Cadd...",Karak_y,"Karak_y, stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz Aac۱,208,stanbul,"Kouyolu Mahallesi, Muhittin st_nda Caddesi, No...",Kouyolu,"Kouyolu, stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,stanbul,"Kuru_eme Mahallesi, Muallim Naci Caddesi, No 5...",Kuru_eme,"Kuru_eme, stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Ak Kahve,208,stanbul,"Kuru_eme Mahallesi, Muallim Naci Caddesi, No 6...",Kuru_eme,"Kuru_eme, stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,stanbul,"Cafeaa Mahallesi, Bademalt۱ Sokak, No 21/B, Ka...",Moda,"Moda, stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [6]:
data=data.drop('Restaurant ID',axis=1)
data.head()

,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant Name       9551 non-null   object
 1   Country Code          9551 non-null   int64
 2   City                  9551 non-null   object
 3   Address               9551 non-null   object
 4   Locality              9551 non-null   object
 5   Locality Verbose      9551 non-null   object
 6   Longitude             9551 non-null   float64
 7   Latitude              9551 non-null   float64
 8   Cuisines              9542 non-null   object
 9   Average Cost for two  9551 non-null   int64
 10  Currency              9551 non-null   object
 11  Has Table booking     9551 non-null   object
 12  Has Online delivery   9551 non-null   object
 13  Is delivering now     9551 non-null   object
 14  Switch to order menu  9551 non-null   object
 15  Price range           9551 non-null   int64
 16  Aggregate rating      9551 non-null   float64
 17  Rating color          9551 non-null   object
 18  Rating text           9551 non-null   object
 19  Votes                 9551 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 1.5+ MB

### **2.1.1 Determine the percentage of restaurants that offer table booking and online delivery.**

In [28]:
c=0
for i in range(len(data)):
    if data['Has Table booking'][i]=='Yes' and data['Has Online delivery'][i]=='Yes':
        c+=1
perc=((c/len(data))*100)
print(f'Out of {len(data)} Restaurants {c} Restaurants have both Table booking, Online delivery \nThat means {perc:.2f}% of Restaurants have both Table booking, Online delivery')

Out of 9551 Restaurants 435 Restaurants have both Table booking, Online delivery
That means 4.55% of Restaurants have both Table booking, Online delivery

### **2.1.2 Compare the average ratings of restaurants with table booking and those without.**

In [39]:
sum_of_ratings_with_table_booking=0
noof_resturants_with_table_booking=0
sum_of_ratings_wo_table_booking=0
noof_resturants_wo_table_booking=0
for i in range(len(data)):
    if data['Has Table booking'][i]=='Yes':
        sum_of_ratings_with_table_booking+=data['Aggregate rating'][i]
        noof_resturants_with_table_booking+=1
        
    else:
        sum_of_ratings_wo_table_booking+=data['Aggregate rating'][i]
        noof_resturants_wo_table_booking+=1


print(sum_of_ratings_with_table_booking,noof_resturants_with_table_booking,sum_of_ratings_wo_table_booking,noof_resturants_wo_table_booking)
Avg_rating_with_booking=((sum_of_ratings_with_table_booking)/(noof_resturants_with_table_booking))
Avg_rating_wo_booking=((sum_of_ratings_wo_table_booking)/(noof_resturants_wo_table_booking))     
print(f'Average ratings of restaurants with table booking {Avg_rating_with_booking:.3f} \nAverage ratings of restaurants without table booking {Avg_rating_wo_booking:.3f}')

3985.799999999998 1158 21480.700000000008 8393
Average ratings of restaurants with table booking 3.442
Average ratings of restaurants without table booking 2.559

### **2.1.3 Analyze the availability of online delivery among restaurants with different price ranges.**

In [44]:
price_ranges=list(data['Price range'].unique())
price_ranges

[3, 4, 2, 1]

In [82]:
d={}
for i in price_ranges:
    d[i]=0
print(d)
for i in range(len(data)):
    if data['Has Online delivery'][i]=='Yes':
        d[data['Price range'][i]]+=1
print(d)
for i in range(len(d)):
    print(f'{list(d.values())[i]} restaurants with {list(d.keys())[i]} price ranges have availability of online delivery.')

{3: 0, 4: 0, 2: 0, 1: 0}
{3: 411, 4: 53, 2: 1286, 1: 701}
411 restaurants with 3 price ranges have availability of online delivery.
53 restaurants with 4 price ranges have availability of online delivery.
1286 restaurants with 2 price ranges have availability of online delivery.
701 restaurants with 1 price ranges have availability of online delivery.

In [81]:
cond=data['Has Online delivery']=='Yes'
len(data[cond]),411+53+1286+701

(2451, 2451)

## **Task 2: Price Range Analysis**
### **2.2.1 Determine the most common price range among all the restaurants.**

In [80]:
d={}
for i in price_ranges:
    d[i]=0
print(d)
for i in range(len(data)):
    d[data['Price range'][i]]+=1

print(d)
print(f'Most common price range among all the restaurants is {list(d.keys())[np.argmax(list(d.values()))]}-Price Range with {np.max(list(d.values()))} no.of Restaurants')

{3: 0, 4: 0, 2: 0, 1: 0}
{3: 1408, 4: 586, 2: 3113, 1: 4444}
Most common price range among all the restaurants is 1-Price Range with 4444 no.of Restaurants

In [64]:
1408+586+3113+4444,len(data)

(9551, 9551)

### **2.2.2 Calculate the average rating for each price range.**

In [93]:
d={}
c={}
avg_rating={}
for i in price_ranges:
    d[i]=0
    c[i]=0
    avg_rating[i]=0
print(d,c,avg_rating)
for i in range(len(data)):
    d[data['Price range'][i]]+=data['Aggregate rating'][i]
    c[data['Price range'][i]]+=1
print(d,c)
for i in price_ranges:
    avg_rating[i]=(d[i]/c[i])
    print(f'Average rating for {i}-price range={avg_rating[i]:.2f}')

{3: 0, 4: 0, 2: 0, 1: 0} {3: 0, 4: 0, 2: 0, 1: 0} {3: 0, 4: 0, 2: 0, 1: 0}
{3: 5186.200000000001, 4: 2237.3000000000025, 2: 9155.500000000013, 1: 8887.500000000005} {3: 1408, 4: 586, 2: 3113, 1: 4444}
Average rating for 3-price range=3.68
Average rating for 4-price range=3.82
Average rating for 2-price range=2.94
Average rating for 1-price range=2.00

- **Average rating for 1st price range=2.00**
- **Average rating for 2nd price range=2.94**
- **Average rating for 3rd price range=3.68**
- **Average rating for 4th price range=3.82**

### **2.2.3 Identify the color that represents the highest average rating among different price ranges.**

In [ ]:
#remaining